// GERADO por tools/build-script-templates.py — nao editar a mao.
//
// Os modelos de comportamento que o editor oferece ao criar um script.
// A fonte e assets/script-templates/*.cs, compilada no teste gerenciado
// AstraTemplateTests: um modelo que nao compila nunca chega aqui.
//
// `className` e substituido pelo nome que o usuario digitar, no codigo e
// no ComponentId. `contracts` marca os modelos que precisam do arquivo de
// contratos, criado junto quando o projeto ainda nao o tem.
#pragma once
#include <array>
#include <string_view>

namespace ae::editor {
struct EditorScriptTemplate {
  std::string_view className;
  std::string_view name;
  std::string_view description;
  bool contracts;
  std::string_view source;
};

inline constexpr std::string_view kEditorScriptContractsFile = "Contratos.cs";
inline constexpr std::string_view kEditorScriptContracts =
    "using Astra;\n"
    "\n"
    "// Os contratos que os comportamentos deste projeto usam para conversar entre si.\n"
    "//\n"
    "// São INTERFACES, não componentes: nada aqui aparece no menu \"Adicionar\". Quem\n"
    "// interage procura por capacidade — \"este objeto sabe ser interagido\?\" — em vez\n"
    "// de procurar por um tipo concreto. É o que permite acrescentar um baú, uma\n"
    "// alavanca ou um elevador depois sem tocar no script que interage.\n"
    "\n"
    "/// <summary>Algo que responde a uma interação do jogador.</summary>\n"
    "public interface IInteragivel\n"
    "{\n"
    "    /// <summary>Texto curto para a interface de jogo mostrar ao mirar.</summary>\n"
    "    string Rotulo { get; }\n"
    "\n"
    "    /// <summary>Executa a interação. `autor` é quem interagiu.</summary>\n"
    "    void Interagir(GameObject autor);\n"
    "}\n"
    "\n"
    "/// <summary>Algo que pode ser coletado e contado.</summary>\n"
    "public interface IColetavel\n"
    "{\n"
    "    int Valor { get; }\n"
    "    void Coletar(GameObject autor);\n"
    "}\n"
    "";

inline constexpr std::array<EditorScriptTemplate,8> editorScriptTemplates{{
  {
    "SeguirAlvo",
    "Seguir alvo",
    "Mantém um deslocamento em relação a outro objeto",
    false,
    "using Astra;\n"
    "using System;\n"
    "using System.Numerics;\n"
    "\n"
    "// Segue um alvo mantendo um deslocamento.\n"
    "//\n"
    "// Não conhece câmera: funciona igual em uma luz, um marcador ou um objeto\n"
    "// qualquer, porque só lê a pose do alvo e escreve a própria. Trocar o modelo, o\n"
    "// nome ou o alvo não muda nada aqui.\n"
    "[ComponentId(\"project.SeguirAlvo\")]\n"
    "public sealed class SeguirAlvo : Behavior\n"
    "{\n"
    "    [PropertyId(\"alvo\")] public ObjectReference Alvo;\n"
    "    [PropertyId(\"deslocamento\")] public Vector3 Deslocamento = new(0, 3, -6);\n"
    "    // Zero segue instantaneamente; valores maiores alcançam mais rápido.\n"
    "    [PropertyId(\"suavidade\")] public float Suavidade = 8;\n"
    "\n"
    "    private GameObject\? _alvo;\n"
    "\n"
    "    public override void Start()\n"
    "    {\n"
    "        // Resolvido UMA vez: procurar por nome todo quadro percorreria a cena\n"
    "        // inteira, e um alvo removido deve parar de ser seguido, não ser\n"
    "        // reencontrado por acaso em outro objeto com o mesmo nome.\n"
    "        if (Resolve(Alvo) is { } encontrado) _alvo = encontrado;\n"
    "    }\n"
    "\n"
    "    public override void Update(float deltaTime)\n"
    "    {\n"
    "        if (_alvo is not { IsAlive: true }) return;\n"
    "        var destino = _alvo.WorldTransform.Position + Deslocamento;\n"
    "        var atual = Object.WorldTransform;\n"
    "        var fator = Suavidade <= 0 \? 1 : Math.Min(1, Suavidade * deltaTime);\n"
    "        Object.WorldTransform = atual with { Position = Vector3.Lerp(atual.Position, destino, fator) };\n"
    "    }\n"
    "}\n"
    ""
  },
  {
    "CameraOrbital",
    "Câmera orbital",
    "Órbita com desvio de obstáculo por varredura",
    false,
    "using Astra;\n"
    "using System;\n"
    "using System.Numerics;\n"
    "\n"
    "// Câmera de órbita que não atravessa parede.\n"
    "//\n"
    "// A distância é reduzida até o primeiro corpo entre o alvo e a câmera, medido\n"
    "// por uma ESFERA varrida: um raio fino entraria por frestas que a câmera não\n"
    "// atravessa, e o resultado seria a câmera encostando na quina.\n"
    "//\n"
    "// A rotação vem da ação de olhar que o projeto configurou — não de um nome fixo\n"
    "// no núcleo. Um jogo que chame essa ação de outra coisa continua funcionando.\n"
    "[ComponentId(\"project.CameraOrbital\")]\n"
    "public sealed class CameraOrbital : Behavior\n"
    "{\n"
    "    [PropertyId(\"alvo\")] public ObjectReference Alvo;\n"
    "    [PropertyId(\"distancia\")] public float Distancia = 6;\n"
    "    [PropertyId(\"altura\")] public float Altura = 1.6f;\n"
    "    [PropertyId(\"raio_da_camera\")] public float RaioDaCamera = .3f;\n"
    "    [PropertyId(\"distancia_minima\")] public float DistanciaMinima = 1;\n"
    "    [PropertyId(\"graus_por_tela\")] public float GrausPorTela = 180;\n"
    "    [PropertyId(\"limite_vertical\")] public float LimiteVertical = 60;\n"
    "\n"
    "    private GameObject\? _alvo;\n"
    "    private float _yaw, _pitch;\n"
    "\n"
    "    public override void Start()\n"
    "    {\n"
    "        if (Resolve(Alvo) is { } encontrado) _alvo = encontrado;\n"
    "    }\n"
    "\n"
    "    public override void Update(float deltaTime)\n"
    "    {\n"
    "        if (_alvo is not { IsAlive: true }) return;\n"
    "\n"
    "        var olhar = Input.Look;\n"
    "        _yaw += olhar.X * GrausPorTela;\n"
    "        _pitch = Math.Clamp(_pitch + olhar.Y * GrausPorTela, -LimiteVertical, LimiteVertical);\n"
    "\n"
    "        const float paraRadianos = MathF.PI / 180;\n"
    "        var rotacao = Quaternion.CreateFromYawPitchRoll(_yaw * paraRadianos, _pitch * paraRadianos, 0);\n"
    "        // A câmera da engine olha ao longo de +Z; a posição fica atrás do foco.\n"
    "        var frente = Vector3.Transform(Vector3.UnitZ, rotacao);\n"
    "        var foco = _alvo.WorldTransform.Position + new Vector3(0, Altura, 0);\n"
    "\n"
    "        var distancia = Distancia;\n"
    "        var filtro = QueryFilter.Default;\n"
    "        // Encostar no próprio personagem não é obstáculo.\n"
    "        filtro.Ignore = _alvo.ObjectId;\n"
    "        var caminho = -frente * Distancia;\n"
    "        if (Physics.ShapeCast(ShapeQuery.Sphere(RaioDaCamera), foco, caminho, filtro) is { } obstaculo)\n"
    "            distancia = Math.Max(DistanciaMinima, obstaculo.Distance);\n"
    "\n"
    "        Object.WorldTransform = new TransformValue(foco - frente * distancia, rotacao, Vector3.One);\n"
    "    }\n"
    "}\n"
    ""
  },
  {
    "Interacao",
    "Interação",
    "Mira à frente e aciona o que estiver sob a mira",
    true,
    "using Astra;\n"
    "using System.Numerics;\n"
    "\n"
    "// Quem interage: olha para a frente, encontra o objeto mirado e chama a\n"
    "// capacidade dele.\n"
    "//\n"
    "// Não conhece porta, baú nem alavanca — procura por CONTRATO (`IInteragivel`).\n"
    "// Acrescentar um tipo novo de coisa interagível não exige tocar neste arquivo.\n"
    "[ComponentId(\"project.Interacao\")]\n"
    "public sealed class Interacao : Behavior\n"
    "{\n"
    "    [PropertyId(\"acao\")] public string Acao = \"Interagir\";\n"
    "    [PropertyId(\"alcance\")] public float Alcance = 2.5f;\n"
    "    [PropertyId(\"camadas\")] public string Camadas = \"\";\n"
    "\n"
    "    private uint _mascara = 0xffffffffu;\n"
    "    private string _rotulo = \"\";\n"
    "\n"
    "    /// <summary>O que está sob a mira agora, para a interface de jogo mostrar.</summary>\n"
    "    public string RotuloAtual => _rotulo;\n"
    "\n"
    "    public override void Start()\n"
    "    {\n"
    "        // A máscara é resolvida uma vez: nomes de camada viram bits aqui, e não\n"
    "        // a cada quadro.\n"
    "        if (!string.IsNullOrEmpty(Camadas)) _mascara = Physics.LayerMask(Camadas.Split(','));\n"
    "    }\n"
    "\n"
    "    public override void Update(float deltaTime)\n"
    "    {\n"
    "        var pose = Object.WorldTransform;\n"
    "        var frente = Vector3.Transform(Vector3.UnitZ, pose.Rotation);\n"
    "\n"
    "        var filtro = QueryFilter.Default;\n"
    "        filtro.LayerMask = _mascara;\n"
    "        filtro.Ignore = ObjectId;\n"
    "        var alvo = Physics.RayCast(pose.Position, frente * Alcance, filtro);\n"
    "\n"
    "        _rotulo = \"\";\n"
    "        if (alvo is not { } acerto) return;\n"
    "        var capacidade = FindBehavior<IInteragivel>(acerto.Object);\n"
    "        if (capacidade is null) return;\n"
    "\n"
    "        _rotulo = capacidade.Rotulo;\n"
    "        // `JustPressed` e não `Pressed`: segurar o botão não pode reabrir a\n"
    "        // porta sessenta vezes por segundo.\n"
    "        if (Input.JustPressed(Acao)) capacidade.Interagir(Object);\n"
    "    }\n"
    "}\n"
    ""
  },
  {
    "Porta",
    "Porta",
    "Abre e fecha ao ser interagida, com ângulo configurável",
    true,
    "using Astra;\n"
    "using System;\n"
    "using System.Numerics;\n"
    "\n"
    "// Uma porta configurável: gira até um ângulo aberto e volta.\n"
    "//\n"
    "// Ela cumpre o contrato `IInteragivel`, então qualquer coisa que saiba interagir\n"
    "// a aciona. O eixo, o ângulo e a velocidade são campos — a mesma porta serve\n"
    "// para um portão que desliza, bastando trocar o eixo e usar deslocamento.\n"
    "[ComponentId(\"project.Porta\")]\n"
    "public sealed class Porta : Behavior, IInteragivel\n"
    "{\n"
    "    [PropertyId(\"rotulo\")] public string Etiqueta = \"Abrir\";\n"
    "    [PropertyId(\"angulo_aberto\")] public float AnguloAberto = 95;\n"
    "    [PropertyId(\"graus_por_segundo\")] public float GrausPorSegundo = 220;\n"
    "    [PropertyId(\"comeca_aberta\")] public bool ComecaAberta;\n"
    "    [PropertyId(\"tranca\")] public bool Trancada;\n"
    "\n"
    "    private float _angulo;\n"
    "    private float _fechado;\n"
    "    private bool _aberta;\n"
    "\n"
    "    public string Rotulo => Trancada \? \"Trancada\" : _aberta \? \"Fechar\" : Etiqueta;\n"
    "\n"
    "    public override void Start()\n"
    "    {\n"
    "        // O ângulo fechado é o que o usuário AUTOROU na cena: a porta não\n"
    "        // assume que nasce alinhada com o eixo do mundo.\n"
    "        _fechado = Object.LocalTransform.Rotation.ToEulerY();\n"
    "        _aberta = ComecaAberta;\n"
    "        _angulo = _aberta \? AnguloAberto : 0;\n"
    "    }\n"
    "\n"
    "    public void Interagir(GameObject autor)\n"
    "    {\n"
    "        if (Trancada) return;\n"
    "        _aberta = !_aberta;\n"
    "    }\n"
    "\n"
    "    public override void Update(float deltaTime)\n"
    "    {\n"
    "        var destino = _aberta \? AnguloAberto : 0;\n"
    "        if (Math.Abs(_angulo - destino) < .01f) return;\n"
    "        var passo = GrausPorSegundo * deltaTime;\n"
    "        _angulo = Math.Abs(destino - _angulo) <= passo \? destino\n"
    "                : _angulo + (destino > _angulo \? passo : -passo);\n"
    "        var atual = Object.LocalTransform;\n"
    "        const float paraRadianos = MathF.PI / 180;\n"
    "        Object.LocalTransform = atual with\n"
    "        {\n"
    "            Rotation = Quaternion.CreateFromYawPitchRoll((_fechado + _angulo) * paraRadianos, 0, 0),\n"
    "        };\n"
    "    }\n"
    "}\n"
    "\n"
    "internal static class PortaMatematica\n"
    "{\n"
    "    /// <summary>Guinada em graus de um quatérnio, na convenção da engine.</summary>\n"
    "    public static float ToEulerY(this Quaternion rotation)\n"
    "    {\n"
    "        var seno = 2 * (rotation.W * rotation.Y + rotation.X * rotation.Z);\n"
    "        var cosseno = 1 - 2 * (rotation.Y * rotation.Y + rotation.X * rotation.X);\n"
    "        return MathF.Atan2(seno, cosseno) * 180 / MathF.PI;\n"
    "    }\n"
    "}\n"
    ""
  },
  {
    "PlataformaMovel",
    "Plataforma móvel",
    "Vai e volta por movimento cinemático",
    false,
    "using Astra;\n"
    "using System;\n"
    "using System.Numerics;\n"
    "\n"
    "// Plataforma cinemática que vai e volta entre dois pontos.\n"
    "//\n"
    "// Ela usa MOVIMENTO FÍSICO (`MoveKinematic`), não escrita de transform: é o\n"
    "// movimento cinemático que faz o solver transportar quem está em cima. Escrever\n"
    "// a pose direto teleportaria a plataforma e deixaria o personagem para trás —\n"
    "// e o mundo de execução recusa essa escrita justamente por isso.\n"
    "[ComponentId(\"project.PlataformaMovel\")]\n"
    "public sealed class PlataformaMovel : Behavior\n"
    "{\n"
    "    [PropertyId(\"deslocamento\")] public Vector3 Deslocamento = new(0, 0, 6);\n"
    "    [PropertyId(\"velocidade\")] public float Velocidade = 2;\n"
    "    [PropertyId(\"espera\")] public float Espera = 1;\n"
    "\n"
    "    private Vector3 _inicio;\n"
    "    private float _progresso;\n"
    "    private float _sentido = 1;\n"
    "    private float _parada;\n"
    "\n"
    "    public override void Start() => _inicio = Object.WorldTransform.Position;\n"
    "\n"
    "    public override void FixedUpdate(float deltaTime)\n"
    "    {\n"
    "        var comprimento = Deslocamento.Length();\n"
    "        if (comprimento <= 0.0001f || Velocidade <= 0) return;\n"
    "\n"
    "        if (_parada > 0)\n"
    "        {\n"
    "            _parada -= deltaTime;\n"
    "            // Continua publicando a pose parada: o contrato cinemático é uma\n"
    "            // pose por passo, e pular passos faria o solver interpolar saltos.\n"
    "            Publicar();\n"
    "            return;\n"
    "        }\n"
    "\n"
    "        _progresso += _sentido * Velocidade * deltaTime / comprimento;\n"
    "        if (_progresso >= 1) { _progresso = 1; _sentido = -1; _parada = Espera; }\n"
    "        else if (_progresso <= 0) { _progresso = 0; _sentido = 1; _parada = Espera; }\n"
    "        Publicar();\n"
    "    }\n"
    "\n"
    "    private void Publicar()\n"
    "    {\n"
    "        var destino = _inicio + Deslocamento * Math.Clamp(_progresso, 0, 1);\n"
    "        Scene.MoveKinematic(ObjectId, destino, Object.WorldTransform.Rotation);\n"
    "    }\n"
    "}\n"
    ""
  },
  {
    "ItemColetavel",
    "Item coletável",
    "Some ao ser tocado ou interagido e soma pontos",
    true,
    "using Astra;\n"
    "\n"
    "// Item que some ao ser tocado ou interagido, somando ao total do coletor.\n"
    "//\n"
    "// Aceita os dois caminhos de propósito: o sensor (encostar) e o contrato de\n"
    "// interação (apertar o botão mirando). Quem conta é o COLETOR, não este script:\n"
    "// o item não sabe quem o pegou, só avisa.\n"
    "[ComponentId(\"project.ItemColetavel\")]\n"
    "public sealed class ItemColetavel : Behavior, IInteragivel, IColetavel\n"
    "{\n"
    "    [PropertyId(\"rotulo\")] public string Etiqueta = \"Pegar\";\n"
    "    [PropertyId(\"valor\")] public int Pontos = 1;\n"
    "    [PropertyId(\"por_contato\")] public bool PorContato = true;\n"
    "\n"
    "    private bool _coletado;\n"
    "\n"
    "    public string Rotulo => Etiqueta;\n"
    "    public int Valor => Pontos;\n"
    "\n"
    "    public void Interagir(GameObject autor) => Coletar(autor);\n"
    "\n"
    "    public void Coletar(GameObject autor)\n"
    "    {\n"
    "        // Uma vez só: o sensor pode reportar Enter e o jogador apertar o botão\n"
    "        // no mesmo quadro, e o item não pode valer dois pontos por isso.\n"
    "        if (_coletado) return;\n"
    "        _coletado = true;\n"
    "        foreach (var contador in FindBehaviors<Coletor>(autor)) contador.Somar(Pontos);\n"
    "        // A remoção entra na fila e é aplicada no ponto seguro; a referência a\n"
    "        // este objeto já vence aqui, e ninguém mais consegue coletá-lo.\n"
    "        Object.Destroy();\n"
    "    }\n"
    "\n"
    "    public override void TriggerEnter(ObjectReference other)\n"
    "    {\n"
    "        if (!PorContato || _coletado) return;\n"
    "        if (Resolve(other) is { } autor) Coletar(autor);\n"
    "    }\n"
    "}\n"
    "\n"
    "// O total de quem coleta. Fica no objeto do jogador, não no item.\n"
    "[ComponentId(\"project.Coletor\")]\n"
    "public sealed class Coletor : Behavior\n"
    "{\n"
    "    [PropertyId(\"total\")] public int Total;\n"
    "\n"
    "    public void Somar(int valor)\n"
    "    {\n"
    "        Total += valor;\n"
    "        Scene.Log(ObjectId, \"coletado total=\" + Total);\n"
    "    }\n"
    "}\n"
    ""
  },
  {
    "TrocaMaterial",
    "Trocar material",
    "Muda cor e emissão da malha por evento",
    true,
    "using Astra;\n"
    "using System.Numerics;\n"
    "\n"
    "// Troca a aparência do objeto quando algo acontece.\n"
    "//\n"
    "// Escreve nas propriedades do componente de Malha pela API comum — as mesmas\n"
    "// propriedades que o Inspector edita, pelos mesmos identificadores. Não existe\n"
    "// um caminho paralelo \"de script\" que aceite o que a interface recusa.\n"
    "[ComponentId(\"project.TrocaMaterial\")]\n"
    "public sealed class TrocaMaterial : Behavior, IInteragivel\n"
    "{\n"
    "    [PropertyId(\"rotulo\")] public string Etiqueta = \"Alternar\";\n"
    "    [PropertyId(\"cor_ligada\")] public Vector3 CorLigada = new(0.15f, 0.85f, 0.35f);\n"
    "    [PropertyId(\"cor_desligada\")] public Vector3 CorDesligada = new(0.6f, 0.6f, 0.6f);\n"
    "    [PropertyId(\"emissao_ligada\")] public float EmissaoLigada = 2;\n"
    "    [PropertyId(\"comeca_ligado\")] public bool ComecaLigado;\n"
    "    // Quando vazio, muda a própria malha; senão, a malha do objeto referenciado.\n"
    "    [PropertyId(\"alvo\")] public ObjectReference Alvo;\n"
    "\n"
    "    private Component\? _malha;\n"
    "    private bool _ligado;\n"
    "\n"
    "    public string Rotulo => Etiqueta;\n"
    "\n"
    "    public override void Start()\n"
    "    {\n"
    "        var alvo = Resolve(Alvo) \?\? Object;\n"
    "        _malha = alvo.GetComponent(ComponentIds.MeshRenderer);\n"
    "        _ligado = ComecaLigado;\n"
    "        Aplicar();\n"
    "    }\n"
    "\n"
    "    public void Interagir(GameObject autor)\n"
    "    {\n"
    "        _ligado = !_ligado;\n"
    "        Aplicar();\n"
    "    }\n"
    "\n"
    "    public override void CollisionEnter(Collision collision)\n"
    "    {\n"
    "        // O mesmo efeito por contato sólido: encostar acende.\n"
    "        if (_ligado) return;\n"
    "        _ligado = true;\n"
    "        Aplicar();\n"
    "    }\n"
    "\n"
    "    private void Aplicar()\n"
    "    {\n"
    "        if (_malha is not { } malha || !malha.IsAlive) return;\n"
    "        var cor = _ligado \? CorLigada : CorDesligada;\n"
    "        malha.SetFloat(\"base_color.r\", cor.X);\n"
    "        malha.SetFloat(\"base_color.g\", cor.Y);\n"
    "        malha.SetFloat(\"base_color.b\", cor.Z);\n"
    "        malha.SetFloat(\"emission.r\", cor.X);\n"
    "        malha.SetFloat(\"emission.g\", cor.Y);\n"
    "        malha.SetFloat(\"emission.b\", cor.Z);\n"
    "        malha.SetFloat(\"emission_strength\", _ligado \? EmissaoLigada : 0);\n"
    "    }\n"
    "}\n"
    ""
  },
  {
    "ControleDeLuz",
    "Controle de luz",
    "Acende, apaga e pulsa uma Luz, nela ou em outro objeto",
    true,
    "using Astra;\n"
    "using System;\n"
    "using System.Numerics;\n"
    "\n"
    "// Acende, apaga e pulsa uma Luz.\n"
    "//\n"
    "// Usa a MESMA API de propriedades que o Inspector: `intensity`, `color.r/g/b`,\n"
    "// `range`. Não existe um caminho paralelo de script para luz — se a interface\n"
    "// recusa um valor fora do intervalo do descritor, aqui também recusa.\n"
    "//\n"
    "// A luz pode estar neste objeto ou em outro: quem quiser um interruptor na\n"
    "// parede acendendo um poste referencia o poste em `alvo`.\n"
    "[ComponentId(\"project.ControleDeLuz\")]\n"
    "public sealed class ControleDeLuz : Behavior, IInteragivel\n"
    "{\n"
    "    [PropertyId(\"rotulo\")] public string Etiqueta = \"Acender\";\n"
    "    [PropertyId(\"alvo\")] public ObjectReference Alvo;\n"
    "    [PropertyId(\"intensidade_acesa\")] public float IntensidadeAcesa = 20;\n"
    "    [PropertyId(\"cor\")] public Vector3 Cor = new(1, 0.92f, 0.78f);\n"
    "    [PropertyId(\"comeca_acesa\")] public bool ComecaAcesa = true;\n"
    "    // Zero deixa a luz parada. Acima disso ela pulsa nessa frequência, em Hz,\n"
    "    // entre `variacao` e a intensidade cheia.\n"
    "    [PropertyId(\"frequencia_pulso\")] public float FrequenciaPulso;\n"
    "    [PropertyId(\"variacao\")] public float Variacao = 0.35f;\n"
    "\n"
    "    private Component\? _luz;\n"
    "    private bool _acesa;\n"
    "    private float _tempo;\n"
    "\n"
    "    public string Rotulo => Etiqueta;\n"
    "\n"
    "    public override void Start()\n"
    "    {\n"
    "        var alvo = Resolve(Alvo) \?\? Object;\n"
    "        _luz = alvo.GetComponent(ComponentIds.Light);\n"
    "        _acesa = ComecaAcesa;\n"
    "        if (_luz is { IsAlive: true } luz)\n"
    "        {\n"
    "            luz.SetFloat(\"color.r\", Cor.X);\n"
    "            luz.SetFloat(\"color.g\", Cor.Y);\n"
    "            luz.SetFloat(\"color.b\", Cor.Z);\n"
    "        }\n"
    "        Aplicar();\n"
    "    }\n"
    "\n"
    "    public void Interagir(GameObject autor)\n"
    "    {\n"
    "        _acesa = !_acesa;\n"
    "        Aplicar();\n"
    "    }\n"
    "\n"
    "    public override void Update(float deltaTime)\n"
    "    {\n"
    "        if (!_acesa || FrequenciaPulso <= 0) return;\n"
    "        _tempo += deltaTime;\n"
    "        Aplicar();\n"
    "    }\n"
    "\n"
    "    private void Aplicar()\n"
    "    {\n"
    "        if (_luz is not { IsAlive: true } luz) return;\n"
    "        if (!_acesa) { luz.SetFloat(\"intensity\", 0); return; }\n"
    "        // Um seno em torno de 1 menos metade da variação: o pico continua sendo\n"
    "        // a intensidade autorada, e o vale desce só o que `variacao` pedir.\n"
    "        var fator = FrequenciaPulso <= 0\n"
    "            \? 1\n"
    "            : 1 - Math.Clamp(Variacao, 0, 1) * 0.5f *\n"
    "                  (1 - MathF.Cos(_tempo * FrequenciaPulso * MathF.Tau));\n"
    "        luz.SetFloat(\"intensity\", MathF.Max(0, IntensidadeAcesa * fator));\n"
    "    }\n"
    "}\n"
    ""
  }
}};

} // namespace ae::editor
