// GERADO por tools/pack-icon-atlas.py — não edite à mão.
#include "ui/ui_icon_id.h"

namespace ae::ui {
namespace {
constexpr const char *kNames[] = {
    "none",
    "assets/animation",
    "assets/bookmark",
    "assets/checker",
    "assets/cloud-download",
    "assets/cloud-upload",
    "assets/copy",
    "assets/docs",
    "assets/download",
    "assets/export",
    "assets/file",
    "assets/file-mesh",
    "assets/filter",
    "assets/folder",
    "assets/folder-open",
    "assets/grid",
    "assets/import",
    "assets/library",
    "assets/list",
    "assets/material",
    "assets/material-checker",
    "assets/package",
    "assets/save",
    "assets/search",
    "assets/static-mesh",
    "assets/texture",
    "assets/upload",
    "assets/video",
    "debug/bug",
    "debug/stats",
    "debug/tools",
    "editor/align",
    "editor/edit-points",
    "editor/focus",
    "editor/frame-object",
    "editor/gizmo-axes",
    "editor/move",
    "editor/orbit",
    "editor/pan",
    "editor/pivot",
    "editor/redo",
    "editor/resize",
    "editor/rotate",
    "editor/scale",
    "editor/select",
    "editor/select-active",
    "editor/select-box",
    "editor/selection-bounds",
    "editor/snap",
    "editor/space-world",
    "editor/undo",
    "lighting/cloud",
    "lighting/cloud-sun",
    "lighting/exposure",
    "lighting/sun",
    "nature/architecture",
    "nature/landscape",
    "nature/leaf",
    "nature/mountains",
    "nature/rock",
    "nature/tree",
    "nature/water",
    "physics/character",
    "primitive/capsule",
    "primitive/cone",
    "primitive/cube",
    "primitive/cylinder",
    "primitive/sphere",
    "runtime/audio",
    "runtime/camera",
    "runtime/camera-orbit",
    "runtime/pause",
    "runtime/play",
    "runtime/restart",
    "runtime/stop",
    "scene/duplicate",
    "scene/flatten",
    "scene/isolate-off",
    "scene/layer-add",
    "scene/layers",
    "scene/lock",
    "scene/object",
    "scene/object-add",
    "scene/object-preview",
    "scene/object-remove",
    "scene/pin",
    "scene/unlock",
    "scene/visibility",
    "scene/visibility-off",
    "scripting/code",
    "scripting/nodes",
    "ui/add",
    "ui/arrow-left",
    "ui/arrow-right",
    "ui/check",
    "ui/chevron-down",
    "ui/chevron-left",
    "ui/chevron-right",
    "ui/chevron-up",
    "ui/close",
    "ui/help",
    "ui/home",
    "ui/info",
    "ui/menu",
    "ui/more-horizontal",
    "ui/more-vertical",
    "ui/panel-left",
    "ui/panel-right",
    "ui/remove",
    "ui/settings",
    "ui/share",
    "ui/sliders",
    "ui/warning",
    "vfx/particles",
    "view/collapse",
    "view/corners",
    "view/expand",
    "view/grid",
    "brand/wordmark",
    "brand/mark",
};
} // namespace

const char *uiIconName(UiIcon icon) noexcept {
  const u32 index = static_cast<u32>(icon);
  return index <= kUiIconCount ? kNames[index] : "unknown";
}

} // namespace ae::ui
