#include "harness.h"
#include "editor/editor_session.h"
#include "editor/editor_archive.h"
#include "editor/editor_creation_catalog.h"
#include "editor/editor_component_visuals.h"
#include "editor/editor_import_transaction.h"
#include "renderer/primitive_geometry.h"
#include "runtime/physics_field2d_sample.h"
#include "scene/component_reflection.h"
#include <filesystem>
#include <chrono>
using namespace ae;
namespace {
bool near(float a,float b,float tolerance=.005f){return std::abs(a-b)<tolerance;}
template<class T> u64 field(runtime::SceneGraph &g,runtime::ObjectId id){auto v=*g.find(id);auto *c=v.components.add(T::descriptor);auto instance=c->instanceId();g.applyEntityValues(id,v);return instance;}
runtime::ObjectId body(runtime::SceneGraph &g,float x,float mass=1,float offset=0){auto id=g.createEntity(g.root(),runtime::ObjectKind::Folder,"Body2D");auto v=*g.find(id);v.transform.position[0]=x;auto *b=static_cast<scene::Body2D*>(v.components.add(scene::Body2D::descriptor));b->mass=mass;b->gravityScale=0;b->linearDamping=b->angularDamping=0;auto *shape=static_cast<scene::Collider2D*>(v.components.add(scene::Collider2D::descriptor));shape->offsetX=offset;g.applyEntityValues(id,v);return id;}
void configure(runtime::SceneGraph &g,runtime::ObjectId id,const scene::ComponentType &type,void (*edit)(scene::PhysicsFieldProperties&)){auto v=*g.find(id);auto *c=static_cast<scene::PhysicsFieldProperties*>(v.components.edit(type));edit(*c);g.applyEntityValues(id,v);}
scene::ScriptSceneAccess access;
scene::ScriptRuntimeApi api(){scene::ScriptRuntimeApi a;a.start=[](const u8*,int,const u8*,int,const scene::ScriptSceneAccess *s){access=*s;return s->available()?0:1;};a.update=[](float){return 0;};a.fixedUpdate=a.lateUpdate=a.update;a.stop=[]{};a.copyDiagnostics=[](u8*,int){return 0;};a.trigger=[](u64,u64,u32){return 0;};a.contact=[](u64,u64,u32,const float*){return 0;};a.timer=[](u64,u64,u32){return 0;};a.lifecycle=[](u32,u32){return 0;};return a;}
}
AE_TEST(fields2d50_creation_vector2_keyboard_archive_undo_and_visuals){
 AE_EXPECT_TRUE(scene::auditComponentContracts().empty(),"XY channels have actual consumers");
 editor::EditorSession session;auto &g=session.document();runtime::ObjectId last=0;
 for(const char *name:{"field2d.gravity","field2d.wind","field2d.drag","field2d.radial"}){
  u32 recipe=0;AE_EXPECT_TRUE(editor::findCreationRecipe(name,&recipe),"creation entry");last=session.createRecipe(recipe,g.root());AE_EXPECT_TRUE(last,"actual composed recipe");auto v=*g.find(last);const auto *component=v.components.at(0);const auto &type=component->type();const auto instance=component->instanceId();
  AE_EXPECT_TRUE(scene::physicsField2DKind(*component)>=0&&type.triples[0].dimensions()==2,"true XY descriptor");
  AE_EXPECT_TRUE(scene::setComponentTriple(v.components,type.id,"offset",{1,2,0},instance)==scene::ComponentPropertyStatus::Applied,"atomic XY");
  AE_EXPECT_TRUE(scene::setComponentTriple(v.components,type.id,"offset",{4,5,1},instance)==scene::ComponentPropertyStatus::InvalidValue,"nonzero transport Z rejected");
  AE_EXPECT_TRUE(scene::setComponentTriple(v.components,type.id,"half_extents",{0,4,0},instance)!=scene::ComponentPropertyStatus::Applied,"zero width rejected atomically");g.applyEntityValues(last,v);
  editor::EditorDocument reopened;AE_EXPECT_TRUE(editor::deserializeEditorDocument(editor::serializeEditorDocument(g,789),789,reopened),"archive reopen");
  const auto *saved=static_cast<const scene::PhysicsFieldProperties*>(reopened.find(last)->components.find(type));AE_EXPECT_TRUE(saved&&near(saved->offset[1],2)&&near(saved->halfExtents[0],3),"exact authored state");
  const auto visuals=editor::collectComponentVisuals(reopened,last,1);AE_EXPECT_TRUE(!visuals.empty()&&visuals.back().segments.size()>=4&&visuals.back().icon!=ui::UiIcon::None,"real XY outline and atlas icon");
 }
 AE_EXPECT_TRUE(session.history().undo(g)&&!g.exists(last)&&session.history().redo(g)&&g.exists(last),"recipe undo/redo");
 session.setSelection(last);auto &state=const_cast<editor::EditorScreenState&>(session.screen());const auto *c=g.find(last)->components.at(0);
 const auto *before=static_cast<const scene::PhysicsFieldProperties*>(c);const std::array<float,2> previousOffset{before->offset[0],before->offset[1]};
 state.numericField=editor::widgetId(editor::EditorWidget::ComponentTripleBase)+(1u<<8);state.numericEntity=last;state.numericInstance=c->instanceId();state.numericProperty="offset";
 const auto request=session.pendingTextEdit();const auto depth=session.history().undoDepth();
 AE_EXPECT_TRUE(!session.completeTextEdit(request,"4 5 6",true)&&session.history().undoDepth()==depth,"keyboard rejects third coordinate without history");
 AE_EXPECT_TRUE(session.completeTextEdit(request,"4,5; 6,5",true)&&session.history().undoDepth()==depth+1,"localized XY keyboard commits once");
 const auto read=[&](){return static_cast<const scene::PhysicsFieldProperties*>(g.find(last)->components.at(0));};
 AE_EXPECT_TRUE(near(read()->offset[0],4.5f)&&near(read()->offset[1],6.5f)&&session.history().undo(g)&&near(read()->offset[0],previousOffset[0])&&near(read()->offset[1],previousOffset[1]),"keyboard edits restore actual pre-edit state");
 // Existing three-channel color/Vector3 writes keep their previous contract.
 scene::Components colors;colors.add(scene::Light::descriptor);AE_EXPECT_TRUE(scene::setComponentTriple(colors,scene::Light::descriptor.id,"color",{.2f,.3f,.4f})==scene::ComponentPropertyStatus::Applied,"RGB remains three channels");
}
AE_TEST(fields2d50_transformed_area_layers_falloff_and_invalid_tilt){
 runtime::SceneGraph g;auto parent=g.createEntity(g.root(),runtime::ObjectKind::Folder,"Parent"),id=g.createEntity(parent,runtime::ObjectKind::Folder,"Area");auto instance=field<scene::GravityField2D>(g,id);runtime::Transform t;t.position[0]=10;t.rotationDegrees[2]=90;t.scale[0]=2;t.scale[1]=3;g.setTransform(parent,t);
 configure(g,id,scene::GravityField2D::descriptor,[](auto &v){v.offset[0]=1;v.shape=1;v.radius=2;v.falloff=1;v.affectedLayer=3;});runtime::PhysicsField2DFrame frame;
 AE_EXPECT_TRUE(runtime::makePhysicsField2DFrame(g,id,*g.find(id)->components.findInstance(instance),frame),"hierarchy affine XY");
 auto center=runtime::samplePhysicsField2D(frame,frame.center,2);AE_EXPECT_TRUE(near(center.acceleration[0],9.81f)&&center.acceleration[2]==0,"orientation changes XY direction without scale amplification");
 const float halfway[2]{frame.center[0]+frame.world[0],frame.center[1]+frame.world[1]};AE_EXPECT_TRUE(near(runtime::samplePhysicsField2D(frame,halfway,2).weight,.5f),"scaled circle is ellipse");AE_EXPECT_TRUE(runtime::samplePhysicsField2D(frame,halfway,1).weight==0,"actual layer filtering");
 configure(g,id,scene::GravityField2D::descriptor,[](auto &v){v.shape=0;v.falloff=2;});runtime::makePhysicsField2DFrame(g,id,*g.find(id)->components.findInstance(instance),frame);AE_EXPECT_TRUE(near(runtime::samplePhysicsField2D(frame,halfway,2).weight,20.f/27),"rectangle smooth falloff");
 configure(g,id,scene::GravityField2D::descriptor,[](auto &v){v.enabled=false;});runtime::makePhysicsField2DFrame(g,id,*g.find(id)->components.findInstance(instance),frame);AE_EXPECT_TRUE(runtime::samplePhysicsField2D(frame,frame.center,2).flags==1,"disabled geometry remains inspectable");
 configure(g,id,scene::GravityField2D::descriptor,[](auto &v){v.enabled=true;});t.rotationDegrees[0]=15;g.setTransform(parent,t);runtime::GameWorld w;runtime::ScenePhysics2D physics;AE_EXPECT_TRUE(w.load(g)&&physics.start(w)&&!physics.advance(1.0/60,w)&&!physics.error().empty(),"tilt fails explicitly in actual runtime");
}
AE_TEST(fields2d50_box2d_gravity_mass_center_wind_drag_radial_and_sleep){
 {runtime::SceneGraph g;auto b=body(g,0);auto v=*g.find(b);static_cast<scene::Body2D*>(v.components.edit(scene::Body2D::descriptor))->gravityScale=2;g.applyEntityValues(b,v);for(u32 n=0;n<2;++n){auto id=g.createEntity(g.root(),runtime::ObjectKind::Folder,"Zero gravity");field<scene::GravityField2D>(g,id);configure(g,id,scene::GravityField2D::descriptor,[](auto &v){v.vector[1]=0;});}runtime::GameWorld w;runtime::ScenePhysics2D physics;AE_EXPECT_TRUE(w.load(g)&&physics.start(w)&&physics.advance(.25,w),"real Box2D replacement");float velocity[2],angular;physics.velocity(b,velocity,angular);AE_EXPECT_TRUE(near(velocity[1],0),"overlap cancels gravity once at solver scale");}
 {runtime::SceneGraph g;auto a=body(g,-10,1),b=body(g,10,2),id=g.createEntity(g.root(),runtime::ObjectKind::Folder,"Wind");field<scene::WindField2D>(g,id);configure(g,id,scene::WindField2D::descriptor,[](auto &v){v.halfExtents[0]=100;v.vector[0]=4;v.coefficient=2;});runtime::GameWorld w;runtime::ScenePhysics2D physics;AE_EXPECT_TRUE(w.load(g)&&physics.start(w),"Box2D wind world");for(u32 n=0;n<60;++n)AE_EXPECT_TRUE(physics.advance(1.0/60,w),"wind step");float va[2],vb[2],angular;physics.velocity(a,va,angular);physics.velocity(b,vb,angular);AE_EXPECT_TRUE(near(va[0],4*(1-std::exp(-2.f)))&&near(vb[0],4*(1-std::exp(-1.f))),"real masses determine response");}
 {runtime::SceneGraph g;auto b=body(g,-5,1,5),id=g.createEntity(g.root(),runtime::ObjectKind::Folder,"COM wind");auto instance=field<scene::WindField2D>(g,id);runtime::GameWorld w;runtime::ScenePhysics2D physics;AE_EXPECT_TRUE(w.load(g)&&physics.start(w),"offset collider mass center");runtime::PhysicsFieldSample sample;float xy[3]{};AE_EXPECT_TRUE(physics.fieldQuery(w,w.handle(id),instance,2,xy,0,sample)==runtime::WorldStatus::Ok&&sample.affectedBodies==1,"COM inside while object origin is outside");AE_EXPECT_TRUE(physics.advance(1.0/60,w),"force uses real COM");float velocity[2],angular;physics.velocity(b,velocity,angular);AE_EXPECT_TRUE(velocity[0]>.05f,"COM membership reaches solver");}
 {runtime::SceneGraph g;auto b=body(g,0),id=g.createEntity(g.root(),runtime::ObjectKind::Folder,"Drag");auto v=*g.find(b);auto *settings=static_cast<scene::Body2D*>(v.components.edit(scene::Body2D::descriptor));settings->velocityX=2;settings->angularVelocityDegrees=120;g.applyEntityValues(b,v);field<scene::DragField2D>(g,id);configure(g,id,scene::DragField2D::descriptor,[](auto &v){v.linearDrag=v.angularDrag=1000;});runtime::GameWorld w;runtime::ScenePhysics2D physics;AE_EXPECT_TRUE(w.load(g)&&physics.start(w)&&physics.advance(1.0/60,w),"strong 2D damping");float velocity[2],angular;physics.velocity(b,velocity,angular);AE_EXPECT_TRUE(velocity[0]>=0&&velocity[0]<.001f&&angular>=0&&angular<.001f,"finite exponential drag without reversal");}
 {runtime::SceneGraph g;auto b=body(g,1),id=g.createEntity(g.root(),runtime::ObjectKind::Folder,"Radial");auto instance=field<scene::RadialField2D>(g,id);configure(g,id,scene::RadialField2D::descriptor,[](auto &v){v.acceleration=0;v.wakeBodies=false;});runtime::GameWorld w;runtime::ScenePhysics2D physics;AE_EXPECT_TRUE(w.load(g)&&physics.start(w),"radial rest world");for(u32 n=0;n<90;++n)AE_EXPECT_TRUE(physics.advance(1.0/60,w),"rest step");AE_EXPECT_TRUE(physics.sleeping(b),"zero-effect field permits real Box2D sleep");w.setProperty({w.handle(id),instance},"acceleration",-6.f);w.setProperty({w.handle(id),instance},"tangential_acceleration",3.f);AE_EXPECT_TRUE(physics.advance(1.0/60,w)&&physics.sleeping(b),"wake false preserves sleep");w.setProperty({w.handle(id),instance},"wake_bodies",true);AE_EXPECT_TRUE(physics.advance(1.0/60,w)&&!physics.sleeping(b),"live field edit wakes body");float velocity[2],angular;physics.velocity(b,velocity,angular);AE_EXPECT_TRUE(near(velocity[0],-.1f)&&near(velocity[1],.05f),"radial plus CCW tangent changes solver XY");}
}
AE_TEST(fields2d50_actual_script_bridge_solver_isolation_live_edit_and_removal){
 editor::EditorDocument g;body(g,-1,1);auto second=body(g,1,2);auto v=*g.find(second);v.layer=1;g.applyEntityValues(second,v);auto three=g.createEntity(g.root(),runtime::ObjectKind::Folder,"3D excluded");v=*g.find(three);v.transform.position[2]=10;auto *b=static_cast<scene::PhysicsBody*>(v.components.add(scene::PhysicsBody::descriptor));b->motion=scene::BodyMotion::Dynamic;v.components.add(scene::Collider::descriptor);g.applyEntityValues(three,v);
 auto id=g.createEntity(g.root(),runtime::ObjectKind::Folder,"Area");auto instance=field<scene::WindField2D>(g,id);v=*g.find(id);auto *script=static_cast<scene::ScriptBehavior*>(v.components.add(scene::ScriptBehavior::descriptor));script->scriptType="Fields2D50";script->source="Fields2D50.cs";g.applyEntityValues(id,v);
 editor::EditorMapScene map;editor::EditorPlayScene play;play.setScriptRuntime(api(),"/test");AE_EXPECT_TRUE(play.start(g,map),"actual ScriptBridge starts both real solvers");const auto handle=play.world().handle(id);float point[3]{};scene::ScriptFieldState result;
 auto query=[&](u32 op){return access.fieldQuery(access.context,id,handle.world,handle.generation,instance,op,point,0,&result);};
 AE_EXPECT_TRUE(access.version==scene::ScriptSceneAccess{}.version&&query(2)&&result.affectedBodies==2&&near(result.affectedMass,3),"2D callback never counts Jolt bodies");
 AE_EXPECT_TRUE(play.world().setTriple({handle,instance},"vector",{8,0,0})==runtime::WorldStatus::Ok&&query(0)&&near(result.windVelocity[0],8)&&result.windVelocity[2]==0,"Vector2 reflected write reaches native sample");
 play.world().setProperty({handle,instance},"affected_layer",u32{1});AE_EXPECT_TRUE(query(2)&&result.affectedBodies==1&&near(result.affectedMass,1),"membership uses actual layer");
 point[2]=1;AE_EXPECT_TRUE(!query(0)&&access.lastStatus(access.context)==u32(runtime::WorldStatus::InvalidArgument),"nonzero XY padding rejected");point[2]=0;
 result.reserved=1;AE_EXPECT_TRUE(!query(0),"payload reserved contract");result={};
 AE_EXPECT_TRUE(!access.fieldQuery(access.context,id,handle.world+1,handle.generation,instance,0,point,0,&result),"foreign world rejected");
 AE_EXPECT_TRUE(!access.fieldQuery(access.context,id,handle.world,handle.generation+1,instance,0,point,0,&result),"stale generation rejected");
 play.world().setProperty({handle,instance},"enabled",false);AE_EXPECT_TRUE(query(1)&&(result.flags&1)&&query(2)&&result.affectedBodies==0,"disabled geometry without physical effect");
 AE_EXPECT_TRUE(play.world().removeComponent({handle,instance})==runtime::WorldStatus::Ok&&query(1),"safe-point removal stays valid before flush");play.world().flush();AE_EXPECT_TRUE(!query(1)&&access.lastStatus(access.context)==u32(runtime::WorldStatus::ComponentMissing),"removed instance rejected");const auto callback=access;play.stop();AE_EXPECT_TRUE(!callback.fieldQuery(callback.context,id,handle.world,handle.generation,instance,0,point,0,&result),"old callbacks stop with world");
}
int benchmarkFields2D(){
 runtime::SceneGraph g;for(u32 n=0;n<96;++n)body(g,float(n)*3);for(u32 n=0;n<32;++n){auto id=g.createEntity(g.root(),runtime::ObjectKind::Folder,"Wind benchmark");field<scene::WindField2D>(g,id);configure(g,id,scene::WindField2D::descriptor,[](auto &v){v.halfExtents[0]=1000;v.coefficient=.05f;});}
 runtime::GameWorld w;runtime::ScenePhysics2D physics;if(!w.load(g)||!physics.start(w))return 1;for(u32 n=0;n<5;++n)if(!physics.advance(1.0/60,w))return 1;
 std::array<double,60> values{};double sum=0;for(auto &value:values){const auto start=std::chrono::steady_clock::now();if(!physics.advance(1.0/60,w))return 1;value=std::chrono::duration<double,std::milli>(std::chrono::steady_clock::now()-start).count();sum+=value;}std::sort(values.begin(),values.end());std::printf("Host Debug: 96 dynamic Box2D bodies, 32 overlapping fields, 60 fixed steps; fields+solver+sync mean=%.3f ms p95=%.3f ms max=%.3f ms\n",sum/60,values[56],values.back());return 0;
}
int writeFields2DProject(const char *directory){
 namespace fs=std::filesystem;std::error_code ec;const auto root=fs::absolute(editor::EditorImportTransaction::fromUtf8(directory),ec);if(ec||(fs::exists(root,ec)&&!fs::is_empty(root,ec)))return 2;fs::create_directories(root/"scenes",ec);if(ec)return 2;fs::create_directories(root/"Scripts",ec);if(ec)return 2;
 std::vector<u8> source;if(!editor::EditorImportTransaction::read(fs::path(AETHER_REPOSITORY_ROOT)/"tests/fixtures/physics/Fields2D50Probe.cs",source)||!editor::EditorImportTransaction::write(root/"Scripts/Fields2D50Probe.cs",source))return 2;
 editor::EditorSession session;if(!session.setProjectDirectory(root.generic_string().c_str()))return 2;std::vector<u8> vertices;std::vector<u32> indices;std::vector<renderer::MapDrawRecord> draws;std::vector<renderer::MapMaterialRecord> materials;if(!renderer::appendPrimitiveLibrary(renderer::MapVertexStride,vertices,indices,draws,materials)||!session.importMap(draws,materials,false,vertices,indices,0))return 2;
 auto &g=session.document();const scene::ComponentType *types[]{&scene::GravityField2D::descriptor,&scene::WindField2D::descriptor,&scene::DragField2D::descriptor,&scene::RadialField2D::descriptor};const char *names[]{"Gravidade XY","Vento XY","Arrasto XY","Radial XY"};
 for(u32 n=0;n<4;++n){auto id=g.createEntity(g.root(),runtime::ObjectKind::Folder,names[n]);auto v=*g.find(id);v.transform.position[0]=float(n)*8-12;v.components.add(*types[n]);if(n==1){auto *s=static_cast<scene::ScriptBehavior*>(v.components.add(scene::ScriptBehavior::descriptor));s->scriptType="acceptance.fields2d50";s->source="Scripts/Fields2D50Probe.cs";}if(!g.applyEntityValues(id,v))return 2;auto b=body(g,float(n)*8-12+(n==3?1:0));v=*g.find(b);std::snprintf(v.name,sizeof(v.name),n==1?"%s":"Corpo: %s",n==1?"Body2D":names[n]);auto *mesh=static_cast<scene::MeshRenderer*>(v.components.add(scene::MeshRenderer::descriptor));mesh->mesh=1;mesh->asset=session.mapScene().assetGuid(0);mesh->material=session.mapScene().materialForAsset(0);auto *settings=static_cast<scene::Body2D*>(v.components.edit(scene::Body2D::descriptor));settings->velocityX=n==2?2:0;if(!g.applyEntityValues(b,v))return 2;}
 auto camera=g.createEntity(g.root(),runtime::ObjectKind::Camera,"Camera XY");auto v=*g.find(camera);auto *lens=static_cast<scene::Camera*>(v.components.add(scene::Camera::descriptor));lens->projection=scene::CameraProjection::Orthographic;lens->orthographicHalfHeight=8;v.transform.position[2]=-24;if(!g.applyEntityValues(camera,v))return 2;
 auto light=g.createEntity(g.root(),runtime::ObjectKind::Folder,"Sol");v=*g.find(light);auto *sun=static_cast<scene::Light*>(v.components.add(scene::Light::descriptor));sun->kind=scene::LightKind::Directional;sun->intensity=10000;v.transform.rotationDegrees[0]=-45;if(!g.applyEntityValues(light,v))return 2;
 const auto data=editor::serializeEditorDocument(g,0);editor::EditorDocument reopened;if(!editor::deserializeEditorDocument(data,0,reopened)||!editor::EditorImportTransaction::writeText(root/"scenes/editor.aescene",data))return 2;
 runtime::GameWorld fixtureWorld;runtime::ScenePhysics2D fixturePhysics;if(!fixtureWorld.load(reopened)||!fixturePhysics.start(fixtureWorld)||!fixturePhysics.advance(1.0/60,fixtureWorld))return 3;
 if(!editor::EditorImportTransaction::writeText(root/"project.json","{\"format\":\"ASTRA-PROJECT-1\",\"resourceSource\":\"independent\",\"project\":{\"name\":\"Fields2D50-20261001\",\"template\":\"empty\",\"scenes\":1,\"assets\":0},\"mainScene\":\"scenes/editor.aescene\",\"editorScene\":\"scenes/editor.aescene\"}"))return 2;
 std::printf("Fields2D50 editable fixture: %s\n",root.generic_string().c_str());return 0;
}
