#pragma once
#include "scene/physics2d_components.h"
#include "scene/physics2d_event_connection.h"
#include "scene/physics_field2d.h"
namespace ae::scene {
inline constexpr std::array<ComponentRule,3> physics2dConflicts{{
 {"astra.physics.body","Corpos 2D e 3D não compartilham o mesmo objeto"},
 {"astra.physics.character","Personagem 3D possui a pose deste objeto"},
 {"astra.physics.collider","Colisores 2D e 3D usam mundos separados"}
}};
inline constexpr std::array<ComponentRule,1> body2dRequirements{{{"astra.physics2d.collider","Adicione uma forma 2D ao corpo"}}};
inline constexpr std::array<ComponentRule,1> body2dRequired{{{"astra.physics2d.body","Adicione Body2D ao objeto"}}};
inline constexpr std::array<ComponentSchema,9> physics2dSchemas{{
 {.type=&GravityField2D::descriptor,.name="Campo de gravidade 2D",.description="Gravidade XY em área sobre corpos dinâmicos 2D",.family=ComponentFamily::Physics2D,.structuralInPlay=PlayMutability::SafePoint,.consumer="runtime/scene_physics2d_fields.inl → Box2D",.subfamily="Campos",.icon="physics/field-gravity-2d",.searchTerms="Area2D Gravity Zone",.reference="https://docs.godotengine.org/en/4.5/classes/class_area2d.html",.apiName="GravityField2D"},
 {.type=&WindField2D::descriptor,.name="Campo de vento 2D",.description="Acoplamento XY à velocidade do ar com massa real",.family=ComponentFamily::Physics2D,.structuralInPlay=PlayMutability::SafePoint,.consumer="runtime/scene_physics2d_fields.inl → Box2D",.subfamily="Campos",.icon="physics/field-wind-2d",.searchTerms="Area2D Wind Vento",.reference="https://docs.godotengine.org/en/4.5/classes/class_area2d.html",.apiName="WindField2D"},
 {.type=&DragField2D::descriptor,.name="Campo de arrasto 2D",.description="Amortecimento linear XY e angular de Body2D",.family=ComponentFamily::Physics2D,.structuralInPlay=PlayMutability::SafePoint,.consumer="runtime/scene_physics2d_fields.inl → Box2D",.subfamily="Campos",.icon="physics/field-drag-2d",.searchTerms="Area2D Damp Drag",.reference="https://docs.godotengine.org/en/4.5/classes/class_area2d.html",.apiName="DragField2D"},
 {.type=&RadialField2D::descriptor,.name="Campo radial 2D",.description="Atração, repulsão e vórtice no plano XY",.family=ComponentFamily::Physics2D,.structuralInPlay=PlayMutability::SafePoint,.consumer="runtime/scene_physics2d_fields.inl → Box2D",.subfamily="Campos",.icon="physics/field-radial-2d",.searchTerms="Area2D Point Gravity Vortex",.reference="https://docs.godotengine.org/en/4.5/classes/class_area2d.html",.apiName="RadialField2D"},
 {.type=&PhysicsEventConnection2D::descriptor,.name="Conexão física 2D",.description="Evento real de sensor/contato 2D altera ativação do receptor",.family=ComponentFamily::Physics2D,.requirements=body2dRequired,.structuralInPlay=PlayMutability::SafePoint,.consumer="runtime/scene_physics_connections.h → GameWorld::setActive antes do callback",.invalidates=Invalidate::PhysicsBody,.subfamily="Eventos",.icon="event/physics-connection-2d",.searchTerms="Area2D Trigger2D Signal Evento Conexao",.reference="https://docs.godotengine.org/en/4.5/classes/class_area2d.html",.apiName="PhysicsEventConnection2D"},
 {.type=&ConstantForce2D::descriptor,.name="Força constante 2D",.description="Força XY e torque contínuos sobre Body2D dinâmico",.family=ComponentFamily::Physics2D,.requirements=body2dRequired,.structuralInPlay=PlayMutability::SafePoint,.consumer="runtime/scene_physics2d.cpp → ApplyForce/ApplyTorque por passo",.subfamily="Forças",.icon="physics/constant-force-2d",.searchTerms="ConstantForce2D RelativeForce Propulsão",.reference="https://docs.unity3d.com/6000.0/Documentation/ScriptReference/ConstantForce2D.html",.apiName="ConstantForce2D"},
 {.type=&Joint2D::descriptor,.name="Junta 2D",.description="Fixed/Weld, Revolute, Prismatic ou Distance reais",.family=ComponentFamily::Physics2D,.requirements=body2dRequired,.structuralInPlay=PlayMutability::SafePoint,.consumer="runtime/scene_physics2d.cpp → Box2D joints",.invalidates=Invalidate::PhysicsBody,.subfamily="Juntas",.icon="physics/joint-2d",.searchTerms="Joint2D FixedJoint2D HingeJoint2D SliderJoint2D DistanceJoint2D Spring",.reference="https://docs.unity3d.com/6000.0/Documentation/ScriptReference/Joint2D.html",.apiName="Joint2D"},
 {.type=&Body2D::descriptor,.name="Corpo 2D",.description="Corpo XY independente de física 3D",.family=ComponentFamily::Physics2D,.requirements=body2dRequirements,.conflicts=physics2dConflicts,.structuralInPlay=PlayMutability::SafePoint,.consumer="runtime/scene_physics2d.cpp → Box2D 3.1.1",.invalidates=Invalidate::PhysicsBody,.subfamily="Corpos",.icon="physics/body-2d",.searchTerms="Rigidbody2D RigidBody2D Kinematic XY",.reference="https://docs.godotengine.org/en/4.5/classes/class_rigidbody2d.html",.apiName="Body2D"},
 {.type=&Collider2D::descriptor,.name="Colisor 2D",.description="Caixa, círculo ou cápsula; sensor real",.family=ComponentFamily::Physics2D,.conflicts=physics2dConflicts,.structuralInPlay=PlayMutability::SafePoint,.consumer="runtime/scene_physics2d.cpp → Box2D 3.1.1",.invalidates=Invalidate::PhysicsShape,.subfamily="Formas",.icon="physics/collider-2d",.searchTerms="CollisionShape2D Box Circle Capsule Sensor Trigger",.reference="https://docs.godotengine.org/en/4.5/classes/class_collisionshape2d.html",.apiName="Collider2D"}
}};
}
