#!/usr/bin/env python3
"""Generate production C++ registrations and typed property accessors in batches.

Inputs are reviewed source contracts, not a runtime interpreter. Existing serializers,
consumers and the C# generator keep consuming ComponentType / ComponentSchema.
--check is read-only and rejects missing, stale, orphaned or disconnected outputs.
"""
from __future__ import annotations
import argparse
import hashlib
import json
from pathlib import Path
import re
import subprocess
import sys

IDENT = re.compile(r"[A-Za-z_][A-Za-z_0-9]*\Z")
MEMBER = re.compile(r"[A-Za-z_]\w*(?:\[\d+\])?(?:\.[A-Za-z_]\w*(?:\[\d+\])?)*\Z")
SCHEMA_FIELDS = ("name", "description", "family", "requirements", "conflicts",
                 "structuralInPlay", "propertiesInPlay", "consumer", "capability",
                 "invalidates", "subfamily", "icon", "searchTerms", "reference",
                 "listedInAdd", "apiName")
PRESENTATION_FIELDS = ("group", "unit", "help", "visible", "editable", "capability",
                       "consumer", "invalidates")


def require(condition, message):
    if not condition:
        raise ValueError(message)


def identifier(value):
    require(isinstance(value, str) and IDENT.fullmatch(value), f"invalid C++ identifier: {value!r}")
    return value


def keys(value, allowed, required=()):
    require(isinstance(value, dict), "expected an object")
    require(not value.keys() - set(allowed), f"unknown fields: {sorted(value.keys() - set(allowed))}")
    require(not set(required) - value.keys(), f"missing fields: {sorted(set(required) - value.keys())}")


def cpp(value):
    if isinstance(value, str):
        return json.dumps(value, ensure_ascii=False)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        require(not isinstance(value, float) or float('-inf') < value < float('inf'), "non-finite number")
        return str(value)
    keys(value, ("cpp",), ("cpp",))
    require(isinstance(value['cpp'], str) and value['cpp'].strip(), "empty C++ expression")
    return value['cpp']


def presentation(value):
    keys(value, PRESENTATION_FIELDS)
    return '{' + ', '.join('.' + key + '=' + cpp(value[key]) for key in PRESENTATION_FIELDS if key in value) + '}'


def merged(defaults, entry):
    result = {**defaults, **entry}
    if 'presentation' in defaults or 'presentation' in entry:
        result['presentation'] = {**defaults.get('presentation', {}), **entry.get('presentation', {})}
    return result


def banner(source):
    return ("// Generated by tools/generate-component-contracts.py. Do not edit.\n"
            f"// Source: {source}\n")


def no_duplicate_keys(pairs):
    result = {}
    for key, value in pairs:
        require(key not in result, f"duplicate JSON key: {key}")
        result[key] = value
    return result


def load(path):
    data = json.loads(path.read_text(encoding='utf-8'), object_pairs_hook=no_duplicate_keys)
    require(data.get('format') == 1, f"unsupported contract format in {path.name}")
    return data


def render(root):
    directory = root / 'tools/component_contracts'
    index = load(directory / 'families.json')
    keys(index, ('format', 'families'), ('families',))
    require(isinstance(index['families'], list) and index['families'], 'empty family registry')
    require(len(set(index['families'])) == len(index['families']), 'duplicate family')
    outputs = {}; bindings = []; native_types = set(); api_names = set(); tables = set()
    sources = [directory / 'families.json']; inclusions = []; joins = []
    for family in index['families']:
        identifier(family)
        path = directory / (family + '.json'); sources.append(path)
        data = load(path)
        keys(data, ('format', 'family', 'table', 'entries', 'defaults'), ('family', 'table', 'entries'))
        keys(data.get('defaults', {}), SCHEMA_FIELDS)
        require(data['family'] == family, f"family mismatch in {path.name}")
        table = identifier(data['table']); require(table not in tables, f"duplicate table: {table}"); tables.add(table)
        require(isinstance(data['entries'], list) and data['entries'], f"empty family: {family}")
        text = banner(path.relative_to(root).as_posix())
        text += f"inline constexpr std::array<ComponentSchema, {len(data['entries'])}> {table}{{{{\n"
        for raw_entry in data['entries']:
            entry = merged(data.get('defaults', {}), raw_entry)
            keys(entry, ('type',) + SCHEMA_FIELDS, ('type', 'name', 'family', 'consumer', 'reference'))
            typ = identifier(entry['type'])
            require(typ not in native_types, f"duplicate native type: {typ}"); native_types.add(typ)
            for field in ('name', 'consumer', 'reference'):
                require(isinstance(entry[field], str) and entry[field].strip(), f"{typ}: missing {field}")
            require(entry['reference'].startswith('https://'), f"{typ}: reference must be a URL")
            if entry.get('apiName'):
                api = identifier(entry['apiName'])
                require(api not in api_names, f"duplicate C# name: {api}"); api_names.add(api)
            text += f"  {{.type=&{typ}::descriptor"
            for field in SCHEMA_FIELDS:
                if field in entry: text += ',\n   .' + field + '=' + cpp(entry[field])
            text += '},\n'
        text += '}};\n'
        output = f'{family}_schemas.inc'; outputs[output] = text
        bindings.append((f'native/scene/schemas/{family}.h', output))
        inclusions.append(f'#include "scene/schemas/{family}.h"')
        joins.append(table)
    outputs['schema_includes.inc'] = banner('tools/component_contracts/families.json') + '\n'.join(inclusions) + '\n'
    outputs['schema_registry.inc'] = banner('tools/component_contracts/families.json') + 'inline constexpr auto componentSchemas = detail::joinComponentSchemas(\n    ' + ',\n    '.join(joins) + ');\n'
    bindings += [('native/scene/component_schema.h', 'schema_includes.inc'), ('native/scene/component_schema.h', 'schema_registry.inc')]
    property_count = 0; property_tables = 0; template_entries = 0; generated_fields = 0; field_owners = set(); enum_properties = 0
    for path in sorted(directory.glob('properties_*.json')):
        sources.append(path); data = load(path)
        keys(data, ('format', 'source', 'tables', 'field_groups'), ('source', 'tables'))
        source = data['source']
        require(isinstance(source, str) and re.fullmatch(r'native/scene/\w+\.h', source), f"invalid source: {source}")
        field_candidates = {}
        for table in data['tables']:
            keys(table, ('name', 'kind', 'template', 'constexpr', 'items', 'defaults'), ('name', 'kind', 'template', 'constexpr', 'items'))
            name = identifier(table['name']); require(name not in tables, f"duplicate table: {name}"); tables.add(name)
            kind = table['kind']; require(kind in ('Number', 'Boolean', 'Enum'), f"unsupported property kind: {kind}")
            keys(table.get('defaults', {}), ('type', 'presentation', 'default') + (('min', 'max', 'step', 'tweenable') if kind == 'Number' else ()))
            require(isinstance(table['template'], bool) and isinstance(table['constexpr'], bool), 'table flags must be boolean')
            require(isinstance(table['items'], list) and table['items'], f"empty property table: {name}")
            text = banner(path.relative_to(root).as_posix())
            if table['template']: text += 'template<class T> '
            text += 'inline ' + ('constexpr' if table['constexpr'] else 'const')
            text += f' std::array<Component{kind}, {len(table["items"])}> {name}{{{{\n'
            ids = set()
            for raw_item in table['items']:
                item = merged(table.get('defaults', {}), raw_item)
                number = kind == 'Number'
                required = ('id', 'label', 'type', 'member') + (('min', 'max', 'step') if number else ('options',) if kind == 'Enum' else ())
                keys(item, required + ('presentation', 'default') + (('tweenable',) if number else ()), required)
                require(isinstance(item['id'], str) and item['id'] and item['id'] not in ids, f"{name}: empty/duplicate property id")
                ids.add(item['id'])
                typ = identifier(item['type']); member = item['member']
                require(isinstance(member, str) and MEMBER.fullmatch(member), f"invalid typed member: {member!r}")
                require(typ != 'T' or table['template'], f"{name}: unbound template parameter")
                if 'default' in item:
                    require(kind != 'Enum', f"{name}: enum defaults require explicit typed field support")
                    require(IDENT.fullmatch(member) and typ != 'T', f"{name}: generated field needs a concrete scalar member")
                    field_candidates[name + '/' + item['id']] = (typ, member, 'float' if number else 'bool', item['default'])
                read = f'static_cast<const {typ}&>(value).{member}'
                write = f'static_cast<{typ}&>(value).{member}'
                metadata = presentation(item.get('presentation', {}))
                if number:
                    text += '  {' + ', '.join(cpp(item[k]) for k in ('label', 'min', 'max', 'step')) + ',\n'
                    text += f'   [](const ComponentValue &value)->const float&{{return {read};}},\n'
                    text += f'   [](ComponentValue &value)->float*{{return &{write};}},\n'
                    text += '   ' + cpp(item['id']) + ', ' + metadata
                    if 'tweenable' in item: text += ', ' + cpp(item['tweenable'])
                elif kind == 'Enum':
                    options = identifier(item['options'])
                    text += '  {' + cpp(item['id']) + ', ' + cpp(item['label']) + ', ' + options + ',\n'
                    text += f'   [](const ComponentValue &value)->u32{{return static_cast<u32>({read});}},\n'
                    text += f'   [](ComponentValue &value,u32 next){{{write}=static_cast<decltype({write})>(next);}},\n   {metadata}'
                    enum_properties += 1
                else:
                    text += '  {' + cpp(item['id']) + ', ' + cpp(item['label']) + ',\n'
                    text += f'   [](const ComponentValue &value)->bool{{return {read};}},\n'
                    text += f'   [](ComponentValue &value,bool next){{{write}=next;}},\n   {metadata}'
                text += '},\n'
            text += '}};\n'
            output = f'{Path(source).stem}_{name}.inc'
            require(output not in outputs, f"duplicate output: {output}"); outputs[output] = text
            bindings.append((source, output)); property_tables += 1; property_count += len(table['items'])
            if table['template']: template_entries += len(table['items'])
        declared_fields = set(); consumed_defaults = set()
        for group in data.get('field_groups', []):
            keys(group, ('name', 'type', 'properties'), ('name', 'type', 'properties'))
            name = identifier(group['name']); typ = identifier(group['type'])
            require(group['properties'], f"empty field group: {name}")
            text = banner(path.relative_to(root).as_posix())
            for ref in group['properties']:
                require(ref in field_candidates, f"missing field default: {ref}")
                owner, member, field_type, default = field_candidates[ref]
                require(owner == typ and (owner, member) not in declared_fields, f"duplicate/mismatched field: {ref}")
                consumed_defaults.add(ref); declared_fields.add((owner, member))
                text += f'  {field_type} {member} = {cpp(default)};\n'
                generated_fields += 1
                field_owners.add(owner)
            output = name + '.inc'; require(output not in outputs, f"duplicate output: {output}")
            outputs[output] = text; bindings.append((source, output))
        require(consumed_defaults == field_candidates.keys(), f"{source}: unused field defaults")
    # An input added but not included is not progress. Fail before writing any output.
    for source, output in bindings:
        include = f'#include "scene/generated/{output}"'
        require((root / source).is_file() and (root / source).read_text(encoding='utf-8').count(include) == 1,
                f"disconnected output {output}: expected exactly one include in {source}")
    expected_inputs = {p.name for p in sources} | {'baseline.json'}
    require(not {p.name for p in directory.glob('*.json')} - expected_inputs, 'unregistered contract input')
    digest = hashlib.sha256()
    for path in sources:
        digest.update(path.name.encode()); digest.update(path.read_bytes())
    report = {'format': 1, 'input_sha256': digest.hexdigest(), 'registered_types': len(native_types),
              'generator_sha256': hashlib.sha256(Path(__file__).read_bytes()).hexdigest(),
              'generated_csharp_facades_from_registry': len(api_names), 'family_tables': len(joins),
              'property_tables': property_tables, 'property_declarations': property_count,
              'template_property_declarations': template_entries, 'generated_accessor_lambdas': property_count * 2,
              'generated_data_fields': generated_fields,
              'types_with_generated_fields': len(field_owners),
              'enum_property_declarations': enum_properties,
              'outputs': {name: hashlib.sha256(text.encode()).hexdigest() for name, text in sorted(outputs.items())},
              'scope': 'Registration, scalar data fields and direct numeric/boolean/enum bindings. Existing consumers and archive methods remain. Not new runtime capabilities or device acceptance.'}
    return outputs, report


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='read-only stale output check')
    parser.add_argument('--report', type=Path, help='write measured generation coverage as JSON')
    parser.add_argument('--sync-api', action='store_true', help='build the lightweight native exporter and update/check the C# API too')
    parser.add_argument('--build-dir', type=Path, default=Path('build/editor-host'), help='configured host CMake build used with --sync-api')
    parser.add_argument('--root', type=Path, default=Path(__file__).resolve().parent.parent)
    args = parser.parse_args()
    try:
        outputs, report = render(args.root)
        directory = args.root / 'native/scene/generated'
        orphans = sorted(p.name for p in directory.glob('*.inc') if p.name not in outputs)
        require(not orphans, f"orphaned generated outputs; review removal explicitly: {orphans}")
        stale = []
        for name, content in outputs.items():
            path = directory / name
            if not path.exists() or path.read_bytes() != content.encode('utf-8'):
                stale.append(name)
        if args.check:
            require(not stale, 'stale generated outputs; run tools/generate-component-contracts.py: ' + ', '.join(stale))
        else:
            directory.mkdir(parents=True, exist_ok=True)
            for name in stale: (directory / name).write_bytes(outputs[name].encode('utf-8'))
        if args.sync_api:
            build = args.build_dir if args.build_dir.is_absolute() else args.root / args.build_dir
            require((build / 'CMakeCache.txt').is_file(), f'configure a host CMake build first: {build}')
            subprocess.run(['cmake', '--build', str(build), '--target', 'aether_component_contract_probe', '--parallel', '2'], check=True)
            binary = build / ('aether_component_contract_probe.exe' if sys.platform == 'win32' else 'aether_component_contract_probe')
            require(binary.is_file(), 'exporter not found; use a single-configuration host build (Ninja)')
            subprocess.run([str(binary), '--check-api' if args.check else '--write-api',
                            str(args.root / 'managed/Astra.Scripting/Generated/Components.g.cs')], check=True)
            report['csharp_api_checked'] = True
        report['check_passed'] = args.check
        report['files_updated'] = 0 if args.check else len(stale)
        if args.report:
            args.report.parent.mkdir(parents=True, exist_ok=True)
            args.report.write_text(json.dumps(report, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
        print(f"{report['registered_types']} types / {report['family_tables']} family tables; "
              f"{report['property_declarations']} property declarations / {report['property_tables']} tables; "
              f"{report['generated_accessor_lambdas']} generated accessors; "
              + ('all outputs current' if args.check else f'{len(stale)} files updated'))
        return 0
    except (ValueError, KeyError, TypeError, OSError, subprocess.CalledProcessError) as error:
        print(f'component codegen: {error}', file=sys.stderr)
        return 1


if __name__ == '__main__':
    raise SystemExit(main())
